import { Poppins, Lexend } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "@/components/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import { ChatbotContextProvider } from "@/context/ChatbotContext";
import MainContentWrapper from "@/components/MainContentWrapper";
import { Toaster } from "react-hot-toast";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Listener-ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${poppins.className} antialiased`}
      >
        <ChatbotContextProvider>
          <ThemeProviderWrapper>
            <div className="relative min-h-screen text-[var(--text-main)]">
              <Toaster/>
              <Sidebar />
              <MainContentWrapper>{children}</MainContentWrapper>
            </div>
          </ThemeProviderWrapper>
        </ChatbotContextProvider>
      </body>
    </html>
  );
}
